apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich
resources:
- ./httproute.yaml
- ./namespace.yaml
- ./postgres.yaml
- ./pvc.yaml
- ./redis.yaml
- ./sealedsecret.yaml

replicas:
- name: immich-machine-learning
  count: 3
- name: immich-server
  count: 3

helmCharts:
- releaseName: immich
  namespace: immich
  name: immich
  repo: oci://ghcr.io/immich-app/immich-charts
  version: 0.10.1
  valuesFile: values.yaml

patches:
- target:
    kind: Deployment
  patch: |
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: immich-config-file
        secret:
          secretName: immich-secret
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: immich-config-file
        mountPath: /config
        readOnly: true
- target:
    kind: Deployment
    name: immich-server
  patch: |
    - op: add
      path: /spec/template/spec/topologySpreadConstraints
      value:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: server
- target:
    kind: Deployment
    name: immich-machine-learning
  patch: |
    - op: add
      path: /spec/template/spec/topologySpreadConstraints
      value:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: machine-learning
