apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: axolotl-lan
  namespace: istio-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: istio
  listeners:
  - name: wildcard-lan-axolotl-cloud
    hostname: "*.lan.axolotl.cloud"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: lan-axolotl-cloud-tls
